# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.
# Project
java_version=[VERSIONED]
# Common
minecraft_version=[VERSIONED]
mod_id=redstone_electronics
# The human-readable display name for the mod.
mod_name=Redstone Electronics
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
license=GPL-3.0-or-later-WITH-Minecraft-linking-exception
# The mod version. See https://semver.org/
version=0.2.0+prealpha.3
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
group=io.codetoil
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_author=Codetoil
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=A mod that adds electronics-inspired redstone blocks to Minecraft.
mod_github=https://github.com/Codetoil/RedstoneElectronics
mod_author_discord=https://discord.gg/m4wJwxf
minecraft_version_range=[VERSIONED]
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=[VERSIONED]
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=[VERSIONED]
parchment_version=[VERSIONED]
# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version=0.17.3
fabric_version=[VERSIONED]
# Quilt
quilt_loader_version=0.29.3-beta.1
quilted_fabric_api_version=[VERSIONED]
# Forge, see https://files.minecraftforge.net/net/minecraftforge/forge/ for new versions
minecraftforge_version=[VERSIONED]
minecraftforge_loader_version_range=[VERSIONED]
# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=[VERSIONED]
neoforge_loader_version_range=[VERSIONED]
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
stonecutter_enabled_platforms=fabric, minecraftforge, neoforge, quilt
stonecutter_enabled_common_versions=1.16.5, 1.18.2, 1.20.1, 1.21.1, 1.21.10
stonecutter_enabled_fabric_versions=1.16.5, 1.18.2, 1.20.1, 1.21.1, 1.21.10
stonecutter_enabled_minecraftforge_versions=1.16.5, 1.18.2, 1.20.1, 1.21.1, 1.21.10
stonecutter_enabled_neoforge_versions=1.21.1, 1.21.10
stonecutter_enabled_quilt_versions=1.20.1, 1.21.1