# Dev
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false
fabric.loom.multiProjectOptimisation=true

# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.
# Project
java_version=[VERSIONED]
# The human-readable display name for the mod.
mod.name=Redstone Electronics
mod.id=redstone_electronics
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod.group=io.codetoil
# The mod version. See https://semver.org/
mod.version=0.2.0+prealpha.3
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod.author=Codetoil
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod.description=A mod that adds electronics-inspired redstone blocks to Minecraft.
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod.license=GPL-3.0-or-later-WITH-Minecraft-linking-exception
mod.credits=a

# Stonecutter
stonecutter_enabled_platforms=fabricmc, neoforge, minecraftforge, quiltmc
stonecutter_enabled_common_versions=1.20.6, 1.21, 1.21.1, 1.21.3, 1.21.4, 1.21.5, 1.21.8, 1.21.10
stonecutter_enabled_fabricmc_versions=1.20.6, 1.21.1, 1.21.3, 1.21.4, 1.21.5, 1.21.8, 1.21.10
stonecutter_enabled_minecraftforge_versions=1.20.6, 1.21.1, 1.21.3, 1.21.4, 1.21.5, 1.21.8, 1.21.10
stonecutter_enabled_neoforge_versions=1.20.6, 1.21.1, 1.21.3, 1.21.4, 1.21.5, 1.21.8, 1.21.10
stonecutter_enabled_quiltmc_versions=1.20.6, 1.21
# Fabric https://fabricmc.net/develop
fabric_loader_version=0.18.1
# Forge https://files.minecraftforge.net/net/minecraftforge/forge
# NeoForge https://projects.neoforged.net/neoforged/neoforge
# Quilt https://quiltmc.org/en/usage/latest-versions
quilt_loader_version=0.29.3-beta.1