modLoader="javafml"
loaderVersion="[40,41)"
license="All rights reserved"

[[mods]]
    modId="redstoneelectronics"
    version="0.2.0"
    displayName="Redstone Electronics"
    authors="Codetoil"
    description='''

    '''
[[dependencies.redstoneelectronics]]
    modId="forge"
    mandatory=true
    versionRange="[40,41)"
    ordering="NONE"
    side="BOTH"
[[dependencies.redstoneelectronics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
