modLoader="javafml"
loaderVersion="[36,37)"
license="All rights reserved"

[[mods]]
    modId="redstoneelectronics"
    version="0.1.1"
    displayName="Redstone Electronics"
    authors="Codetoil"
    description='''

    '''
[[dependencies.redstoneelectronics]]
    modId="forge"
    mandatory=true
    versionRange="[36,37)"
    ordering="NONE"
    side="BOTH"
[[dependencies.redstoneelectronics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
