modLoader="javafml"
loaderVersion="[40,41)"
license="GNU General Public License v3.0 or later"

[[mods]]
    modId="redstoneelectronics"
    version="0.2.0+prealpha.2"
    displayName="Redstone Electronics"
    authors="Codetoil"
    description='''

    '''
[[dependencies.redstoneelectronics]]
    modId="forge"
    mandatory=true
    versionRange="[40,41)"
    ordering="NONE"
    side="BOTH"
[[dependencies.redstoneelectronics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
