name: build
on: [ pull_request, push, release ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            packages: write
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v6
            -   name: Validate Gradle Wrapper
                uses: gradle/wrapper-validation-action@v1
            -   name: Setup JDK
                uses: actions/setup-java@v5
                with:
                    distribution: temurin
                    java-version: 21
                    cache: gradle
            -   name: Build with Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: build
                    gradle-version: 9.2.1
            -   name: Capture Artifacts
                uses: actions/upload-artifact@v5
                with:
                    name: Build
                    path: build/libs/