# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: publish
on: [pull_request, push]

jobs:
  publish:
    strategy:
      matrix:
        # Use these Java distrbutions
        dist: [
          temurin
        ]
        # Use these Java versions
        java: [
          17,    # Current LTS version of Java & minimum supported by Minecraft
          18,
          19     # Latest Java
        ]
        # and run only on Linux
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.dist }}-${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.dist }}
          java-version: ${{ matrix.java }}
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: Gradle Caches
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
          gradle-version: 7.6
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}